query Home($limit: Int = 10) {
  published_posts(limit: $limit, order_by: {published_at: desc}) {
    id
    content
    published_at
    profile {
      id
      display_name
      avatar_url
      handle
    }
    slug
    updated_at
  }
}
