previewsEnabled: true
previewsExpireAfterDays: 3
services:
  # Web app static files
  - type: web
    name: sskk-client-web-static
    env: static
    branch: main
    buildCommand:
      cd client-web && yarn install --frozen-lockfile && yarn build:client
    staticPublishPath: client-web/dist/client
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: https://sskk-web-server.onrender.com/*
    envVars:
      - fromGroup: vite-vars
  # Web app renderer
  - type: web
    name: sskk-client-web-renderer
    env: node
    branch: main
    region: oregon
    plan: starter
    buildCommand: cd client-web && yarn install --frozen-lockfile && yarn build
    startCommand: cd client-web && yarn serve
    healthCheckPath: /
    envVars:
      - fromGroup: vite-vars
      - key: SSR_SECRET
        generateValue: true
  # Actions service, for hasura
  - type: pserv
    name: sskk-service-actions
    env: node
    branch: main
    region: oregon
    plan: starter
    buildCommand:
      cd service-actions && yarn install --frozen-lockfile && yarn build
    startCommand: cd service-actions && yarn start
    envVars:
      - fromGroup: firebase-secrets
      - key: PORT
        value: 10000
      - key: ACTION_SECRET
        fromService:
          name: sskk-service-hasura
          type: web
          envVarKey: ACTION_SECRET
      - key: COOKIE_SIGNING_SECRET
        generateValue: true
      - key: SSR_SECRET
        fromService:
          name: sskk-client-web-renderer
          type: web
          envVarKey: SSR_SECRET
      - key: HASURA_GRAPHQL_PROTOCOL
        value: https
      - key: HASURA_GRAPHQL_HOST_AND_PORT
        fromService:
          type: web
          name: sskk-service-hasura
          property: hostport
      - key: HASURA_ADMIN_SECRET
        fromService:
          name: sskk-service-hasura
          type: web
          envVarKey: HASURA_GRAPHQL_ADMIN_SECRET
  # The hasura service
  - type: web
    name: sskk-service-hasura
    env: docker
    dockerfilePath: ./service-hasura/Dockerfile
    dockerContext: ./service-hasura
    branch: main
    region: oregon
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 8080
      - key: PG_DATABASE_URL
        fromDatabase:
          name: sskk-db-hasura
          property: connectionString
      - key: HASURA_GRAPHQL_METADATA_DATABASE_URL
        fromDatabase:
          name: sskk-db-hasura
          property: connectionString
      - key: HASURA_GRAPHQL_EXPERIMENTAL_FEATURES
        value: inherited_roles
      - key: HASURA_GRAPHQL_ENABLE_CONSOLE
        value: false
      - key: HASURA_GRAPHQL_ADMIN_SECRET
        generateValue: true
        previewValue: "Preview please!"
      - key: HASURA_GRAPHQL_AUTH_HOOK
        value: http://sskk-service-actions:10000/authenticate
      - key: HASURA_GRAPHQL_AUTH_HOOK_MODE
        value: POST
      - key: ACTION_SECRET
        generateValue: true # will generate a base64-encoded 256-bit secret
      - key: ACTION_BASE_PROTOCOL
        value: https
      - key: ACTION_BASE_HOST_AND_PORT
        fromService:
          name: sskk-service-actions
          type: pserv
          property: hostport

databases:
  - name: sskk-db-hasura
    databaseName: sskk_db_hasura # optional (Render may add a suffix)
    ipAllowList: [] # only allow internal connections

envVarGroups:
  - name: firebase-secrets
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false # placeholder for a value to be added in the dashboard
  - name: vite-vars
    envVars:
      - key: VITE_GRAPHQL_HOST_AND_PORT
        value: sskk-service-hasura.onrender.com
      - key: VITE_GRAPHQL_PROTOCOL
        value: https
      - key: VITE_REFRESH_TOKEN_ENDPOINT
        value: https://us-central1-sskk-dev.cloudfunctions.net/refreshCustomerToken
        previewValue: https://us-central1-sskk-dev.cloudfunctions.net/refreshCustomerToken
      - key: VITE_FIREBASE_CONFIG
        value: '{"apiKey":"AIzaSyC4SkkXdvp2CnizuRB5O9flXH0wqi-82rU","authDomain":"sskk-dev.firebaseapp.com","projectId":"sskk-dev","storageBucket":"sskk-dev.appspot.com","messagingSenderId":"294518583561","appId":"1:294518583561:web:2e57050e5e31f334d9a3d8"}'
        previewValue: '{"apiKey":"AIzaSyC4SkkXdvp2CnizuRB5O9flXH0wqi-82rU","authDomain":"sskk-dev.firebaseapp.com","projectId":"sskk-dev","storageBucket":"sskk-dev.appspot.com","messagingSenderId":"294518583561","appId":"1:294518583561:web:2e57050e5e31f334d9a3d8"}'
