previewsEnabled: true
previewsExpireAfterDays: 3
services:
  # Web app static files
  - type: web
    name: sskk-client-web-static
    env: static
    branch: main
    buildCommand: cd client-web && yarn install && yarn build:client
    staticPublishPath: client-web/dist/client
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: https://sskk-web-server.onrender.com/*
    envVars:
      - fromGroup: vite-vars
      - key: VITE_GRAPHQL_HOST_AND_PORT
        fromService:
          name: sskk-service-hasura
          type: web
          property: hostport
  # Web app renderer
  - type: web
    name: sskk-client-web-renderer
    env: node
    branch: main
    region: oregon
    plan: starter
    buildCommand: cd client-web && yarn install && yarn build
    startCommand: cd client-web && yarn serve
    healthCheckPath: /
    envVars:
      - fromGroup: vite-vars
      - key: VITE_GRAPHQL_HOST_AND_PORT
        fromService:
          name: sskk-service-hasura
          type: web
          property: hostport
  # Actions service, for hasura
  - type: pserv
    name: sskk-service-actions
    env: node
    branch: main
    region: oregon
    plan: starter
    buildCommand: cd service-actions && yarn install && yarn build
    startCommand: cd service-actions && yarn start
    envVars:
      - key: ACTION_SECRET
        fromService:
          name: sskk-service-hasura
          type: web
          envVarKey: ACTION_SECRET
      - key: COOKIE_SIGNING_SECRET
        generateValue: true
      - key: HASURA_GRAPHQL_PROTOCOL
        value: https
      - key: HASURA_GRAPHQL_HOST_AND_PORT
        fromService:
          type: web
          name: sskk-service-hasura
          property: hostport
      - key: HASURA_ADMIN_SECRET
        fromService:
          name: sskk-service-hasura
          type: web
          envVarKey: HASURA_GRAPHQL_ADMIN_SECRET
  # The hasura service
  - type: web
    name: sskk-service-hasura
    env: docker
    initialDeployHook: ./service-hasura/seed-database.sh
    branch: main
    region: oregon
    healthCheckPath: /heathz
    envVars:
      - key: PORT
        value: 10000
      - key: HASURA_GRAPHQL_METADATA_DATABASE_URL
        fromDatabase:
          name: sskk-db-hasura
          property: connectionString
      - key: PG_DATABASE_URL
        fromDatabase:
          name: sskk-db-hasura
          property: connectionString
      - key: HASURA_GRAPHQL_EXPERIMENTAL_FEATURES
        value: inherited_roles
      - key: HASURA_GRAPHQL_ENABLE_CONSOLE
        value: false
      - key: HASURA_GRAPHQL_ADMIN_SECRET
        generateValue: true
        previewValue: "Preview please!"
      - key: ACTION_SECRET
        generateValue: true # will generate a base64-encoded 256-bit secret
      - key: ACTION_BASE_PROTOCOL
        value: https
      - key: ACTION_BASE_HOST_AND_PORT
        fromService:
          name: sskk-service-actions
          type: pserv
          property: hostport

databases:
  - name: sskk-db-postgres
    databaseName: hasura # optional (Render may add a suffix)
    ipAllowList: [] # only allow internal connections

envVarGroups:
  - name: vite-vars
    envVars:
      - key: VITE_GRAPHQL_PROTOCOL
        value: https
      - key: VITE_REFRESH_TOKEN_ENDPOINT
        value: https://us-central1-sskk-dev.cloudfunctions.net/refreshCustomerToken
        previewValue: https://us-central1-sskk-dev.cloudfunctions.net/refreshCustomerToken
      - key: VITE_FIREBASE_CONFIG
        value: '{"apiKey":"AIzaSyC4SkkXdvp2CnizuRB5O9flXH0wqi-82rU","authDomain":"sskk-dev.firebaseapp.com","projectId":"sskk-dev","storageBucket":"sskk-dev.appspot.com","messagingSenderId":"294518583561","appId":"1:294518583561:web:2e57050e5e31f334d9a3d8"}'
        previewValue: '{"apiKey":"AIzaSyC4SkkXdvp2CnizuRB5O9flXH0wqi-82rU","authDomain":"sskk-dev.firebaseapp.com","projectId":"sskk-dev","storageBucket":"sskk-dev.appspot.com","messagingSenderId":"294518583561","appId":"1:294518583561:web:2e57050e5e31f334d9a3d8"}'
