query Story($handle: String!, $post_id: uuid!) {
  published_posts(where: {id: {_eq: $post_id}, profile: {handle: {_eq: $handle}}}) {
    id
    content
    published_at
    profile {
      id
      display_name
      avatar_url
      handle
    }
    slug
    updated_at
  }
}
