version: "3.7"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    build: .
    ports:
      - "3711:3711"
    depends_on:
      - "postgres"
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PORT: 3711
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES:
        startup, http-log, webhook-log, websocket-log, query-log
      # HASURA_GRAPHQL_ADMIN_SECRET: Galf,galf77
      # HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      # HASURA_GRAPHQL_JWT_SECRET:
      #   '{"type":"RS256","jwk_url":
      #   "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com","audience":
      #   "sskk-dev","issuer": "https://securetoken.google.com/sskk-dev"}'
volumes:
  db_data:
