schema: "http://localhost:3711/v1/graphql"
documents: ./src/**/*.graphql
extensions:
  endpoints:
    default:
      url: "https://sskk-graphql.herokuapp.com/v1/graphql"
      headers:
        x-hasura-admin-secret: "Im4gln,5w023"