# Example vars:
# {
#   "profile_id": "48b4f201-cfbf-4196-a046-19fe293d1320",
#   "first_version": {
#    	"content": {"test": true},
#    	"editor_state": {"test": true},
#     "title": "Test",
#   	"slug": "test"
#   }
# }
mutation CreatePost($profile_id: uuid!, $first_version: post_versions_insert_input!) {
  insert_posts_one(object: {profile_id: $profile_id, post_versions: {data: [$first_version]}}) {
    id
    created_at
    deleted_at
    published_at
    post_versions {
      content
      editor_state
      id
      locked_for_publication
      slug
      title
    }
  }
}

# Example vars:
# {
#   "post_id": "6dc7cbb1-5033-4bcc-96fe-f2b6e66e9ebe",
#   "published_at": "2021-01-06T00:00:00Z"
# }
mutation PublishPost($post_id: uuid!, $published_at: timestamp!) {
  update_post_versions(where: {post_id: {_eq: $post_id}}, _set: {locked_for_publication: true}) {
    returning {
      id
      locked_for_publication
    }
  }
  update_posts_by_pk(pk_columns: {id: $post_id}, _set: {published_at: $published_at}) {
    latest_version_id
    latest_version_locked_for_publication
    latest_version_slug
    published_at
  }
}

# mutation SavePostDraft($profile_id: uuid!, $first_version: post_versions_insert_input!) {
#   insert_posts_one(object: {profile_id: $profile_id, post_versions: {data: [$first_version]}}) {
#     id
#     created_at
#     deleted_at
#     published_at
#     post_versions {
#       content
#       editor_state
#       id
#       locked_for_publication
#       slug
#       title
#     }
#   }
# }

